name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: docker login
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
      - name: docker build nginx
        run: |
          docker build -t rneezar2/scrumpoker-app-nginx ./nginx
      - name: docker build server
        run: |
          docker build -t rneezar2/scrumpoker-app-server ./packages/api
      - name: docker push
        run: |
          docker push rneezar2/scrumpoker-app-nginx
          docker push rneezar2/scrumpoker-app-server
